#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="${PROJECT_ROOT}/.venv"
ENV_FILE="${PROJECT_ROOT}/.env"

# ---------- colours ----------
if [[ -t 1 ]]; then
  BOLD='\033[1m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; RESET='\033[0m'
else
  BOLD=''; GREEN=''; YELLOW=''; CYAN=''; RESET=''
fi

info()    { printf "${CYAN}▶${RESET}  %s\n" "$*"; }
success() { printf "${GREEN}✔${RESET}  %s\n" "$*"; }
warn()    { printf "${YELLOW}!${RESET}  %s\n" "$*"; }

usage() {
  cat <<EOF
Usage:
  ./start.sh [--docker | --venv] [--test] [--no-reload] [-h]

Modes (prompted interactively if not specified):
  --docker     Build image and start with Docker Compose
  --venv       Create Python venv, install deps, start with uvicorn

Flags:
  --test       Run the test suite (venv mode only)
  --no-reload  Disable uvicorn hot-reload (venv mode only)
  -h, --help   Show this message

Environment (venv mode):
  HOST   bind address  (default: 127.0.0.1)
  PORT   port          (default: 8000)
EOF
}

# ---------- parse args ----------
MODE=""
RUN_TESTS=false
RELOAD_FLAG="--reload"

for arg in "$@"; do
  case "$arg" in
    --docker)    MODE="docker" ;;
    --venv)      MODE="venv" ;;
    --test)      RUN_TESTS=true ;;
    --no-reload) RELOAD_FLAG="" ;;
    -h|--help)   usage; exit 0 ;;
    *)
      printf 'Unknown argument: %s\n\n' "$arg" >&2
      usage; exit 1 ;;
  esac
done

# ---------- interactive mode picker ----------
if [[ -z "${MODE}" ]]; then
  printf '\n%b%bGroupware Migrator%b\n\n' "${BOLD}" "${CYAN}" "${RESET}"
  printf '  1)  Docker   — build image, start with docker compose\n'
  printf '  2)  Venv     — create Python venv, start with uvicorn\n'
  printf '\n'
  read -rp "Choose [1/2]: " _choice
  case "${_choice}" in
    1) MODE="docker" ;;
    2) MODE="venv" ;;
    *) printf 'Invalid choice.\n' >&2; exit 1 ;;
  esac
fi

# ---------- .env bootstrap ----------
setup_env() {
  if [[ -f "${ENV_FILE}" ]]; then
    success ".env exists — skipping setup"
    return
  fi

  info "No .env found — creating one now"
  printf '\n'

  read -rp "  Admin email     [admin@example.com]: " _email
  SETUP_EMAIL="${_email:-admin@example.com}"

  read -rsp "  Admin password  [changeme]: " _pass
  printf '\n'
  SETUP_PASSWORD="${_pass:-changeme}"

  _jwt="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"

  cat > "${ENV_FILE}" <<ENVEOF
# Groupware Migrator — environment configuration
# Generated by start.sh on $(date -u '+%Y-%m-%d %H:%M UTC')

ADMIN_EMAIL=${SETUP_EMAIL}
ADMIN_PASSWORD=${SETUP_PASSWORD}

# Auto-generated — change this in production
JWT_SECRET=${_jwt}

# ── Optional ─────────────────────────────────────────────────────────────────

# Set to true behind a reverse proxy with HTTPS
# COOKIE_SECURE=true

# Public URL used in email notification links
# SITE_URL=https://migrate.example.com

# Session lifetime in hours (default: 8)
# JWT_TTL_HOURS=8

# PostgreSQL — SQLite is used when absent
# DATABASE_URL=postgresql://user:password@localhost:5432/groupware

# Redis — distributed job queue worker
# REDIS_URL=redis://localhost:6379

# Fernet key for encrypting scheduled job credentials at rest
# Generate: python3 -c "import secrets,base64; print(base64.urlsafe_b64encode(secrets.token_bytes(32)).rstrip(b'=').decode())"
# VAULT_KEY=

# ── Email notifications ───────────────────────────────────────────────────────
# SMTP_HOST=smtp.example.com
# SMTP_PORT=587
# SMTP_USER=noreply@example.com
# SMTP_PASSWORD=
# SMTP_FROM=noreply@example.com
# SMTP_TLS=starttls

# ── LDAP / Active Directory ───────────────────────────────────────────────────
# LDAP_HOST=dc.corp.example.com
# LDAP_PORT=389
# LDAP_BASE_DN=OU=Users,DC=corp,DC=example
# LDAP_BIND_DN=CN=svc-migrator,OU=SvcAccts,DC=corp,DC=example
# LDAP_BIND_PASSWORD=
# LDAP_USER_FILTER=(userPrincipalName={email})
# LDAP_DEFAULT_ROLE=operator
ENVEOF

  printf '\n'
  success ".env created (JWT_SECRET auto-generated)"
  printf '\n'
}

# ---------- docker mode ----------
run_docker() {
  if ! command -v docker &>/dev/null; then
    printf 'Error: docker is not installed or not in PATH.\n' >&2
    printf 'Get it at https://docs.docker.com/get-docker/\n' >&2
    exit 1
  fi

  if ! docker compose version &>/dev/null 2>&1; then
    printf 'Error: docker compose plugin not found.\n' >&2
    printf 'Install Docker Desktop or the Compose plugin: https://docs.docker.com/compose/install/\n' >&2
    exit 1
  fi

  setup_env

  info "Building image and starting containers..."
  docker compose up --build -d

  printf '\n'
  success "Groupware Migrator is running at http://localhost:8000"
  printf '\n'
  printf '  Logs:   %bdocker compose logs -f%b\n' "${BOLD}" "${RESET}"
  printf '  Stop:   %bdocker compose down%b\n'    "${BOLD}" "${RESET}"
  printf '\n'
}

# ---------- venv mode ----------
run_venv() {
  if [[ "${RUN_TESTS}" == "true" ]] && [[ ! -d "${VENV_DIR}" ]]; then
    info "Creating virtual environment..."
    python3 -m venv "${VENV_DIR}"
  elif [[ ! -d "${VENV_DIR}" ]]; then
    info "Creating virtual environment at ${VENV_DIR}..."
    python3 -m venv "${VENV_DIR}"
  fi

  # shellcheck source=/dev/null
  source "${VENV_DIR}/bin/activate"

  info "Installing dependencies..."
  python3 -m pip install -e "${PROJECT_ROOT}" -q

  if [[ "${RUN_TESTS}" == "true" ]]; then
    info "Running tests..."
    printf '\n'
    PYTHONPATH="${PROJECT_ROOT}/src" python3 -m unittest discover -s "${PROJECT_ROOT}/tests" -v
    exit 0
  fi

  setup_env

  # Load .env into the current shell so uvicorn inherits all vars
  set -a
  # shellcheck source=/dev/null
  source "${ENV_FILE}"
  set +a

  HOST="${HOST:-127.0.0.1}"
  PORT="${PORT:-8000}"

  printf '\n'
  success "Starting at http://${HOST}:${PORT}"
  printf '\n'

  if [[ -n "${RELOAD_FLAG}" ]]; then
    exec uvicorn groupware_migrator.api.app:create_app \
      --factory --host "${HOST}" --port "${PORT}" "${RELOAD_FLAG}"
  else
    exec uvicorn groupware_migrator.api.app:create_app \
      --factory --host "${HOST}" --port "${PORT}"
  fi
}

# ---------- dispatch ----------
case "${MODE}" in
  docker) run_docker ;;
  venv)   run_venv ;;
esac
